---
apiVersion: v1
kind: Secret
metadata:
  name: cragr-cragr-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus2/cragr-backend-gitops
